VAR CLUSTERS = ['ADRIATICA',
    'AMAZONA', 'ANTARCTICA',
    'AQUA', 'ARABIANA',
    'ARCTICA', 'ATLANTICA',
    'BEVERELEE', 'CASPIANA', 'COLUMBIA',
    'DIONNA', 'ERWINA', 'EXOTICA', 'GARDENIA',
    'GENEVIA', 'GENEVIEVE', 'GIARDINO', 'IRVETTA',
    'MAGDELENA', 'MARINA', 'MEDITERRANEA', 'MORGANA',
    'MURIEL', 'NAUTICA', 'NYASIA', 'OCEANIA', 'PACIFICA',
    'PERSIANA', 'RHINE', 'RILLETTA', 'RIVER DALE',
    'RIVER RETREAT', 'RIVER VIEW',
    'RIVERSCAPE', 'VICTORIA',
    'VIVA', 'VIVIANA', 'VOLGA'
]